const LOG_ERROR_MSG_PREFIX = "EOFOL ERROR - "

const ID_GENERATED_LENGTH = 17

const PROPS_EXCLUDED = ["name", "as"]

const COMPONENT_TYPE_CUSTOM = "custom"
const COMPONENT_TYPE_FLAT = "flat"
const COMPONENT_TYPE_STATIC = "static"
const COMPONENT_TYPE_VIRTUAL = "virtual"

const COMPONENT_ATTRIBUTE_TYPE = "name"

const HANDLER_SERIALIZED_PROPS = "props"
const HANDLER_SERIALIZED_STATE = "state"
const HANDLER_SERIALIZED_SETSTATE = "setState"

const ID_PLACEHOLDER = "@@id@@"

const CUSTOM_DEFAULT_AS_TAGNAME = "div"
const FLAT_DEFAULT_AS_TAGNAME = "div"
const STATIC_DEFAULT_AS_TAGNAME = "div"

const ASSET_LINK_INTERNAL = "linkInternal"
const ASSET_LINK_EXTERNAL = "linkExternal"
const ASSET_IMAGE_DYNAMIC = "imageDynamic"
const ASSET_IMAGE_STATIC = "imageStatic"

const ASSET_STATUS_FETCHING = "FETCHING"
const ASSET_STATUS_FETCHED = "FETCHED"

export default {
  LOG_ERROR_MSG_PREFIX,
  ID_GENERATED_LENGTH,
  PROPS_EXCLUDED,
  COMPONENT_TYPE_CUSTOM,
  COMPONENT_TYPE_FLAT,
  COMPONENT_TYPE_STATIC,
  COMPONENT_ATTRIBUTE_TYPE,
  HANDLER_SERIALIZED_PROPS,
  HANDLER_SERIALIZED_STATE,
  HANDLER_SERIALIZED_SETSTATE,
  ID_PLACEHOLDER,
  COMPONENT_TYPE_VIRTUAL,
  CUSTOM_DEFAULT_AS_TAGNAME,
  FLAT_DEFAULT_AS_TAGNAME,
  STATIC_DEFAULT_AS_TAGNAME,
  ASSET_IMAGE_STATIC,
  ASSET_IMAGE_DYNAMIC,
  ASSET_LINK_EXTERNAL,
  ASSET_LINK_INTERNAL,
  ASSET_STATUS_FETCHING,
  ASSET_STATUS_FETCHED,
}
