const LOG_ERROR_MSG_PREFIX = "EOFOL ERROR - "

const ID_GENERATED_LENGTH = 17

const PROPS_EXCLUDED = ["name", "as"]

const COMPONENT_TYPE_CUSTOM = "custom"
const COMPONENT_TYPE_FLAT = "flat"
const COMPONENT_TYPE_STATIC = "static"

const CUSTOM_COMPONENT_TAGNAME = "custom"
const FLAT_COMPONENT_TAGNAME = "flat"
const STATIC_COMPONENT_TAGNAME = "static"

const COMPONENT_ATTRIBUTE_TYPE = "name"

const HANDLER_SERIALIZED_PROPS = "props"
const HANDLER_SERIALIZED_STATE = "state"
const HANDLER_SERIALIZED_SETSTATE = "setState"

export default {
  LOG_ERROR_MSG_PREFIX,
  ID_GENERATED_LENGTH,
  PROPS_EXCLUDED,
  COMPONENT_TYPE_CUSTOM,
  COMPONENT_TYPE_FLAT,
  COMPONENT_TYPE_STATIC,
  CUSTOM_COMPONENT_TAGNAME,
  COMPONENT_ATTRIBUTE_TYPE,
  FLAT_COMPONENT_TAGNAME,
  STATIC_COMPONENT_TAGNAME,
  HANDLER_SERIALIZED_PROPS,
  HANDLER_SERIALIZED_STATE,
  HANDLER_SERIALIZED_SETSTATE,
}
